services:
  frontend:
    build:
      context: ../invox-client
      dockerfile: Dockerfile
      target: development
    volumes:
      - ../invox-client:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - backend
      - frontend
    environment:
      - NODE_ENV=${NODE_ENV}
      - VITE_APP_KEYCLOAK_REALM=${VITE_APP_KEYCLOAK_REALM}
      - VITE_APP_KEYCLOAK_CLIENTID=${VITE_APP_KEYCLOAK_CLIENTID}
      - VITE_APP_KEYCLOAK_URL=${VITE_APP_KEYCLOAK_URL}
      - VITE_APP_API_BASE_URL=${VITE_APP_API_BASE_URL}
  
  backend:
    build:
      context: ../invox-backend
      dockerfile: Dockerfile
      target: npm_dev_install
    ports:
      - "3001:3001"
    volumes:
      - ../invox-backend:/usr/src/app
      - ../invox-backend/src/data:/usr/src/app/dist/data:ro
      - /usr/src/app/node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_SERVER_URL=${KEYCLOAK_SERVER_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_SECRET=${KEYCLOAK_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - backend
      - frontend
  opensearch:
    image: opensearchproject/opensearch:2.13.0
    container_name: opensearch
    environment:
      - discovery.type=single-node                 # run as a single node (dev)
      - DISABLE_SECURITY_PLUGIN=true            # no auth/TLS for local dev
      - bootstrap.memory_lock=true                 # avoid swapping (nice-to-have)
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g         # adjust if your RAM is tight
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data # persist indices across restarts
    ports:
      - "9200:9200"                                 # OpenSearch REST API
    networks:
      - backend                                     # reachable as http://opensearch:9200 from backend
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.13.0
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200     # talk to the service name on the backend network
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true     # matches security off in OpenSearch
    depends_on:
      opensearch:
        condition: service_healthy
    ports:
      - "5601:5601"                                 # Web UI at http://localhost:5601
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:5601/api/status >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20


  webserver:
    image: nginx:1-alpine
    ports:
      - "4201:4201"
    restart: always
    depends_on:
      - frontend
      - backend
    networks:
      - frontend
      - backend
    volumes:
      - ./config/webserver/nginx/templates/server-variables.conf.template:/etc/nginx/templates/server-variables.conf.template:ro
      - ./config/webserver/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    cap_add:
      - NET_ADMIN

networks:
  frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
  backend:
    name: backend


volumes:
  opensearch-data:

