services:
  
  backend:
    build:
      context: ../invox-backend
      dockerfile: Dockerfile
      target: npm_dev_install
    ports:
      - "3001:3001"
    volumes:
      - ../invox-backend:/usr/src/app
      - ../invox-backend/src/data:/usr/src/app/dist/data:ro
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: npm run start:dev
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=${INVOX_DB_HOST}
      - DB_PORT=${INVOX_DB_PORT}
      - DB_NAME=${INVOX_DB_NAME}
      - DB_USER=${INVOX_DB_USER}
      - DB_PASSWORD=${INVOX_DB_PASSWORD}
      - ENABLE_UNSAFE_EXTRACT=true
    networks:
      - backend
  webserver:
    image: nginx:1-alpine
    ports:
      - "4201:4201"
    restart: always
    depends_on:
      - backend
    networks:
      - backend
    volumes:
      - ./config/webserver/nginx/templates/server-variables.conf.template:/etc/nginx/templates/server-variables.conf.template:ro
      - ./config/webserver/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    cap_add:
      - NET_ADMIN

networks:
  backend:
    name: backend

