services:
  webserver:
    image: nginx:1-alpine
    ports:
      - 80:80
    restart: always
    networks:
      - frontend
      - internal_network
    volumes:
      # the nginx configuration, e.g. how to redirect
      - ./config/webserver/nginx/templates/server-variables.conf.template:/etc/nginx/templates/server-variables.conf.template:ro
      - ./config/webserver/nginx/nginx_cert.conf:/etc/nginx/nginx.conf:ro
      # the certificates
      - ./volumes/letsencrypt:/etc/letsencrypt:ro
      # here the client single page application is stored
      - './volumes/html/:/usr/share/nginx/html:ro'
      # here letsencrypt stores the acme-challenge for verification
      - './volumes/acme-challenge/:/var/www/certbot/:ro'
    environment:
      - EMAIL=${SERVICE_EMAIL}
      - URL=${SERVICE_URL}
      - TZ=Europe/Berlin
    cap_add:
      - "NET_ADMIN"

  certbot:
    image: certbot/certbot:latest
    networks:
      - frontend
    volumes:
      # for the acme challenge
      - './volumes/acme-challenge/:/var/www/certbot/:rw'
      # for the certificates
      - ./volumes/letsencrypt:/etc/letsencrypt
    environment:
      - EMAIL=${SERVICE_EMAIL}
      - URL=${SERVICE_URL}
      - TZ=Europe/Berlin

networks:
  frontend:
    name: frontend
    external: true
  internal_network:
    name: "internal_network"
    internal: true
